/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopupRouteImport } from './routes/topup'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TestCancelledRouteImport } from './routes/test-cancelled'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SellRouteImport } from './routes/sell'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsTotpRouteImport } from './routes/tools.totp'
import { Route as ToolsMailRouteImport } from './routes/tools.mail'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as ApiPublicTopupPollRouteImport } from './routes/api/public/topup/poll'
import { Route as ApiPublicHooksXRefreshRouteImport } from './routes/api/public/hooks/x-refresh'
import { Route as ApiPublicBoostHealthCheckRouteImport } from './routes/api/public/boost/health-check'

const TopupRoute = TopupRouteImport.update({
  id: '/topup',
  path: '/topup',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TestCancelledRoute = TestCancelledRouteImport.update({
  id: '/test-cancelled',
  path: '/test-cancelled',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsTotpRoute = ToolsTotpRouteImport.update({
  id: '/totp',
  path: '/totp',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsMailRoute = ToolsMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => ToolsRoute,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTopupPollRoute = ApiPublicTopupPollRouteImport.update({
  id: '/api/public/topup/poll',
  path: '/api/public/topup/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksXRefreshRoute = ApiPublicHooksXRefreshRouteImport.update({
  id: '/api/public/hooks/x-refresh',
  path: '/api/public/hooks/x-refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBoostHealthCheckRoute =
  ApiPublicBoostHealthCheckRouteImport.update({
    id: '/api/public/boost/health-check',
    path: '/api/public/boost/health-check',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounts': typeof AccountsRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/history': typeof HistoryRoute
  '/profile': typeof ProfileRoute
  '/sell': typeof SellRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/test-cancelled': typeof TestCancelledRoute
  '/tools': typeof ToolsRouteWithChildren
  '/topup': typeof TopupRoute
  '/order/$id': typeof OrderIdRoute
  '/tools/mail': typeof ToolsMailRoute
  '/tools/totp': typeof ToolsTotpRoute
  '/tools/': typeof ToolsIndexRoute
  '/api/public/boost/health-check': typeof ApiPublicBoostHealthCheckRoute
  '/api/public/hooks/x-refresh': typeof ApiPublicHooksXRefreshRoute
  '/api/public/topup/poll': typeof ApiPublicTopupPollRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounts': typeof AccountsRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/history': typeof HistoryRoute
  '/profile': typeof ProfileRoute
  '/sell': typeof SellRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/test-cancelled': typeof TestCancelledRoute
  '/topup': typeof TopupRoute
  '/order/$id': typeof OrderIdRoute
  '/tools/mail': typeof ToolsMailRoute
  '/tools/totp': typeof ToolsTotpRoute
  '/tools': typeof ToolsIndexRoute
  '/api/public/boost/health-check': typeof ApiPublicBoostHealthCheckRoute
  '/api/public/hooks/x-refresh': typeof ApiPublicHooksXRefreshRoute
  '/api/public/topup/poll': typeof ApiPublicTopupPollRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounts': typeof AccountsRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/history': typeof HistoryRoute
  '/profile': typeof ProfileRoute
  '/sell': typeof SellRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/test-cancelled': typeof TestCancelledRoute
  '/tools': typeof ToolsRouteWithChildren
  '/topup': typeof TopupRoute
  '/order/$id': typeof OrderIdRoute
  '/tools/mail': typeof ToolsMailRoute
  '/tools/totp': typeof ToolsTotpRoute
  '/tools/': typeof ToolsIndexRoute
  '/api/public/boost/health-check': typeof ApiPublicBoostHealthCheckRoute
  '/api/public/hooks/x-refresh': typeof ApiPublicHooksXRefreshRoute
  '/api/public/topup/poll': typeof ApiPublicTopupPollRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accounts'
    | '/admin'
    | '/cart'
    | '/catalog'
    | '/history'
    | '/profile'
    | '/sell'
    | '/services'
    | '/sitemap.xml'
    | '/support'
    | '/test-cancelled'
    | '/tools'
    | '/topup'
    | '/order/$id'
    | '/tools/mail'
    | '/tools/totp'
    | '/tools/'
    | '/api/public/boost/health-check'
    | '/api/public/hooks/x-refresh'
    | '/api/public/topup/poll'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accounts'
    | '/admin'
    | '/cart'
    | '/catalog'
    | '/history'
    | '/profile'
    | '/sell'
    | '/services'
    | '/sitemap.xml'
    | '/support'
    | '/test-cancelled'
    | '/topup'
    | '/order/$id'
    | '/tools/mail'
    | '/tools/totp'
    | '/tools'
    | '/api/public/boost/health-check'
    | '/api/public/hooks/x-refresh'
    | '/api/public/topup/poll'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accounts'
    | '/admin'
    | '/cart'
    | '/catalog'
    | '/history'
    | '/profile'
    | '/sell'
    | '/services'
    | '/sitemap.xml'
    | '/support'
    | '/test-cancelled'
    | '/tools'
    | '/topup'
    | '/order/$id'
    | '/tools/mail'
    | '/tools/totp'
    | '/tools/'
    | '/api/public/boost/health-check'
    | '/api/public/hooks/x-refresh'
    | '/api/public/topup/poll'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountsRoute: typeof AccountsRoute
  AdminRoute: typeof AdminRoute
  CartRoute: typeof CartRoute
  CatalogRoute: typeof CatalogRoute
  HistoryRoute: typeof HistoryRoute
  ProfileRoute: typeof ProfileRoute
  SellRoute: typeof SellRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  TestCancelledRoute: typeof TestCancelledRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  TopupRoute: typeof TopupRoute
  OrderIdRoute: typeof OrderIdRoute
  ApiPublicBoostHealthCheckRoute: typeof ApiPublicBoostHealthCheckRoute
  ApiPublicHooksXRefreshRoute: typeof ApiPublicHooksXRefreshRoute
  ApiPublicTopupPollRoute: typeof ApiPublicTopupPollRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topup': {
      id: '/topup'
      path: '/topup'
      fullPath: '/topup'
      preLoaderRoute: typeof TopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-cancelled': {
      id: '/test-cancelled'
      path: '/test-cancelled'
      fullPath: '/test-cancelled'
      preLoaderRoute: typeof TestCancelledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/totp': {
      id: '/tools/totp'
      path: '/totp'
      fullPath: '/tools/totp'
      preLoaderRoute: typeof ToolsTotpRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/mail': {
      id: '/tools/mail'
      path: '/mail'
      fullPath: '/tools/mail'
      preLoaderRoute: typeof ToolsMailRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/topup/poll': {
      id: '/api/public/topup/poll'
      path: '/api/public/topup/poll'
      fullPath: '/api/public/topup/poll'
      preLoaderRoute: typeof ApiPublicTopupPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/x-refresh': {
      id: '/api/public/hooks/x-refresh'
      path: '/api/public/hooks/x-refresh'
      fullPath: '/api/public/hooks/x-refresh'
      preLoaderRoute: typeof ApiPublicHooksXRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/boost/health-check': {
      id: '/api/public/boost/health-check'
      path: '/api/public/boost/health-check'
      fullPath: '/api/public/boost/health-check'
      preLoaderRoute: typeof ApiPublicBoostHealthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ToolsRouteChildren {
  ToolsMailRoute: typeof ToolsMailRoute
  ToolsTotpRoute: typeof ToolsTotpRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsMailRoute: ToolsMailRoute,
  ToolsTotpRoute: ToolsTotpRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountsRoute: AccountsRoute,
  AdminRoute: AdminRoute,
  CartRoute: CartRoute,
  CatalogRoute: CatalogRoute,
  HistoryRoute: HistoryRoute,
  ProfileRoute: ProfileRoute,
  SellRoute: SellRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  TestCancelledRoute: TestCancelledRoute,
  ToolsRoute: ToolsRouteWithChildren,
  TopupRoute: TopupRoute,
  OrderIdRoute: OrderIdRoute,
  ApiPublicBoostHealthCheckRoute: ApiPublicBoostHealthCheckRoute,
  ApiPublicHooksXRefreshRoute: ApiPublicHooksXRefreshRoute,
  ApiPublicTopupPollRoute: ApiPublicTopupPollRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
